import type { Metadata } from "next";
import { Nunito, Open_Sans, Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-nunito",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});
const opensans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-opensans",
});

export const metadata: Metadata = {
  title: "Comprehensive List of Labs in Nigeria - Find a  Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
   const DynamicHeader = dynamic(() => import("./components/Navbar"), {
     ssr: false,
   });

  return (
    <html
      lang="en"
      className={`${playfair.variable} ${nunito.variable} ${poppins.variable} ${opensans.variable}`}
    >
      <body>
        <DynamicHeader />

        {children}
      </body>
    </html>
  );
}
